name: Use CI Pipeline from Central Repo

on:
  pull_request:
    branches:
      - main

jobs:
  trigger-central-workflow:
    uses: Max3kkk/repo-context-analyzer/.github/workflows/ci-pipeline.yml@main
    with:
      github_token: ${{ secrets.MY_GITHUB_TOKEN }}
